### ISSUE TITLE
Grandstream OID not working

### ISSUE THREAD

**Issue by will-code-for-pizza** [thost96/pimatic-snmp#3]
Hi... The following snmp call for firmware status works with my Grandstream IP phones for smnp v 1, 2c and 3:

$ snmpwalk -v 2c -a SHA -x AES -A test1234 -X test1234 -u admin -c public 192.168.1.10 iso.3.6.1.4.1.42397.1.3.3.4.0.0

-->
iso.3.6.1.4.1.42397.1.3.3.4.0.0 = STRING: "1.0.9.127"

but in PiMatic plugin, the same oid results in "No Such Object"

Regards

**Comment by thost96** [comment]
@will-code-for-pizza  try the following command for testing: 
snmpwalk -v 2c -a SHA -x AES -A test1234 -X test1234 -u admin -c public 192.168.1.10 1.3.6.1.4.1.42397.1.3.3.4.0.0

After that try the same oid in pimatic. The iso. isn't a valid value.
